### ISSUE TITLE
Я убью тебя, лодочник

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/animated-slider_react_ts_styled-components#1]
![image](https://user-images.githubusercontent.com/101792032/183435295-cf813595-ffd7-4230-b40e-5d21478b7f2b.png)

Как мне сделать чтобы это говно было не 600х400 ?

**Comment by mordvinian** [comment]
По сути, любая такая библиотечная структура должна быть адаптивной. 
Если ты не знаешь, в какой парадигме и контексте ее будут использовать, делай чтоб была резиновая.
Ширина должна быть 100% от обертки

**Comment by mordvinian** [comment]
Т.к. критерии использования твоего кода неизвестны (ты пишешь библиотечный слайдер в вакууме), он должен быть готов к разным сценариям.

Т.к. настройки ширины делать не просили, сделай универсальную 100% ширину. Тогда тот, кто хочет использовать слайдер, просто положит его в обертку-адаптер

**Comment by mordvinian** [comment]
![image](https://user-images.githubusercontent.com/101792032/183436646-6cefea86-c0c5-4b59-b537-352846d727a4.png)
Туда же

**Comment by VKNagibin** [comment]
Эта issue из старого слайдера на setTimeout-ах
