### ISSUE TITLE
Чет как-то недопонял походу

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/animated-slider_react_ts_styled-components#10]
![image](https://user-images.githubusercontent.com/101792032/184813999-d4c5e3ec-ee0d-4e30-a45c-8f481380296f.png)

Чтобы не писать `gen.next()` три раза подряд, ты можешь убрать ненужные yield в самом генераторе.

Чтобы не писать `gen.next()` в самом начале, ты можешь сделать обертку, которая:
1. создает новый генератор
2. заводит его вызовом `next`
3. возвращает уже заведенный слайдер

**Comment by VKNagibin** [comment]
9746712
