### ISSUE TITLE
Если я не передам текст приложение падает

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/animated-slider_react_ts_styled-components#3]
![image](https://user-images.githubusercontent.com/101792032/183437567-c5256dc6-9af7-4631-9115-a01225e2810b.png)
![image](https://user-images.githubusercontent.com/101792032/183437608-7cbcd0fa-83a7-42c1-8c4d-cb93c50f8f51.png)

**Comment by VKNagibin** [comment]
Эта issue из старого слайдера на setTimeout-ах
