### ISSUE TITLE
Нипанятна

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/animated-slider_react_ts_styled-components#4]
![image](https://user-images.githubusercontent.com/101792032/183438610-4756bbeb-f221-48de-b8e0-614bee2fee93.png)

Как минимум эти кондишны стоит вынести в маленькие подфункции, потому что что за условие непонятно.
Почему 0.8 это какое-то важное значение?

**Comment by VKNagibin** [comment]
Эта issue из старого слайдера на setTimeout-ах
