### ISSUE TITLE
Нет

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/animated-slider_react_ts_styled-components#5]
![image](https://user-images.githubusercontent.com/101792032/183439372-28437477-039e-4d04-9239-bac3a68997e0.png)

Шаблонные методы следует выносить в паттерн "Template method",

Две одинаковые функции находятся в разных местах. Сделай чтобы была одна

**Comment by VKNagibin** [comment]
Это старая issue из кривого слайдера
