### ISSUE TITLE
UX очень плох

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/animated-slider_react_ts_styled-components#6]
Я пока не смотрел с чем это связано, но работает плохо

1. Анимация проигрывается только до середины
2. Почему-то когда листаешь влево картинку не видно
![image](https://user-images.githubusercontent.com/101792032/184811155-1ebf9110-73b8-4ec6-88d8-0d014e52f71d.png)

**Comment by mordvinian** [comment]
![image](https://user-images.githubusercontent.com/101792032/184811821-5d744a0c-83ef-4a91-8628-12b66cc3fce4.png)

Стилистика как у патибоя конечно, ну да ладно

**Comment by VKNagibin** [comment]
c50e108
