### ISSUE TITLE
Не пользуйся сокращениями

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/animated-slider_react_ts_styled-components#7]
![image](https://user-images.githubusercontent.com/101792032/184812013-ead3433d-b0d5-4322-b9b6-55e1e56bb48b.png)

`current`, `generator` или `generatorInstance` даже.

**Comment by mordvinian** [comment]
Не дай бог еще придем к крестовым `std::cout` именам, это ж мрак. 
Такое и читать, и понимать, и озвучивать сложно.

**Comment by mordvinian** [comment]
`standartLibrary::consoleOutputStream` если че перевел для тебя

**Comment by VKNagibin** [comment]
2e8fafa
