### ISSUE TITLE
Nope

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/animated-slider_react_ts_styled-components#8]
![image](https://user-images.githubusercontent.com/101792032/184812437-052662a7-9129-46b2-ae6a-c6858d4f44cf.png)

Вообще я тебе говорил сделать чтобы было 100% ширина, высота в зависимости от контента. Тогда тот, кто использует модуль уже сделает подходящий сокет, куда вставит твой слайдер.

Если будет вариант быстро переделать -  переделай

**Comment by VKNagibin** [comment]
c50e108
