### ISSUE TITLE
Is это для предикатов

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/animated-slider_react_ts_styled-components#9]
![image](https://user-images.githubusercontent.com/101792032/184812954-5b076622-f223-4640-a14d-256217a19e87.png)

Не надо использовать Is в именах таких функций, т.к. ожидается такое использование

`if (animationIsFinished()) {...}` 

Предикат - функция которая не имеет сайд-эффектов и возвращает буль. 

Обычно пишут `isCardNotEmpty` `isUserExist` и др.
Начинают с `is` и дальше описывают, че за условие проверяется.

У тебя же это не вопрос, а утверждение, анимация закончена.

Лучше будет `setAnimationFinished`

**Comment by VKNagibin** [comment]
Понял понял a56562c
